TITLE GABA neurotransmitters injection

NEURON {
	POINT_PROCESS gabpuff
	USEION gab READ gabo VALENCE 0
	USEION mess READ messi WRITE messi VALENCE 0
    RANGE gabo, time0, GABAINIT, GABAdur, temp
}

UNITS {	
	(mM)    = (milli/liter)
}

PARAMETER {
	GABAdur = 0.1		(ms)
}

ASSIGNED {
	gabo		(mM)		: transmitter concentration
	messi		(mM)
	time0		(ms)
	GABAINIT	(mM)
	temp
}

INITIAL { 
	gabo   = 0		(mM)
	GABAINIT = 0	(mM)
	messi = 0 		(mM)
	temp = 0
}

BREAKPOINT {
	if (GABAINIT > 0) {
		if (temp == 0) {
			messi = GABAINIT
			temp = 1
		}
	}
	else { messi = 0 }
}


NET_RECEIVE(weight(mM), nspike) {
	: an onset event (generated by NetStim) always has an implicit argument called flag which is set to 0
	if (flag == 0) {
		nspike = nspike + 1
		time0 = t
		GABAINIT  = weight
		: come again in Cdur with flag = current value of nspike (selfevent generated with delay Cdur & flag=nspike)
		net_send(GABAdur, nspike)
	}
	if (flag == nspike) {
		: if this associated with last spike then turn off
		GABAINIT = 0
	}
}

